### PR TITLE
fixes for purescript 0.9.1

### PR DESCRIPTION
**Pull request by asvyazin**
Just upgraded package versions and fixed compile errors

### CODE REVIEW

**Comment by passy** [comment]
Thanks so much, @asvyazin! Looks like Travis CI got hung up on something. I've just retriggered the build.

**Comment by passy** [comment]
I think this is still currently blocked on https://github.com/hdgarrood/purescript-sequences/pull/23. Did you get it to run the tests locally? I still run into a bunch of dependency issues.

**Comment by asvyazin** [comment]
Well, actually, yes... It works locally for me. And it does not depend on purescript-sequences even recursively

**Comment by asvyazin** [comment]
BTW I'm using newer version of node.js (6.2.1) and windows 10 instead of linux. I'm not sure it matters though...
I will try to run tests on ubuntu and see what happens

**Comment by asvyazin** [comment]
It works on my ubuntu too:
https://gist.github.com/asvyazin/6831df91a5f25f12d9d20481ab1f56ff

**Comment by passy** [comment]
@asvyazin Thanks for testing again. I've tried it on a Mac and it works fine, too! So it's definitely not your patch. I'll investigate the test hang separately.

Cheers for the PR! 🎉

**Pull request merged**
