### PR TITLE
Upgrade to PureScript 0.15.x

### PR DESCRIPTION
**Pull request by CarstenKoenig**
Hello,

here are the changes I needed to get this library running with PureScript 0.15.2.

Everything builds with spago.
Bower is able to download/install the deps and pulp builds and runs the test.

I hope you'll find this helpful.

Thanks for your work.

### CODE REVIEW

**Comment by paluh** [comment]
@passy Should I review this and merge?

**Comment by CarstenKoenig** [comment]
Hi,

I would really appreciate the merge (as I could hopefully get rid of the overrides to my fork).
Feel free to ask for changes/clarification - I happily provide both.

Thanks again.

**Comment by paluh** [comment]
@CarstenKoenig thanks a lot for the PR. ~May I drop the default comments from `packages.dhall` and `spago.dhall`?~ I created a PR to you branch with `spago` comment removal.

@passy I will allow myself to merge this :-)

**Comment by CarstenKoenig** [comment]
Hi - of course!
Feel free to change anything you like.

**Comment by paluh** [comment]
Once again, thanks @CarstenKoenig!

**Comment by CarstenKoenig** [comment]
Thanks for merging

**Pull request merged**
